# -*- coding: utf-8 -*-
import json
out = r"C:\Users\heath\AppData\Local\Temp\claude\C--Users-heath\ecf8983a-6aaa-432f-ad4e-54d4208d5f82\scratchpad\agent-out\agent08.jsonl"
rows = [
{"n":159,"kind":"screenshot - Q post","description":"Screenshot of Q post No. 99 (tripcode !UW.yye1fxo) dated 02/16/18, reading '[UK] - Stay Alert. Q'. The post's attached image is a dark nighttime elevated view of a multi-lane city street with heavy traffic, streetlights, and pedestrians. A yellow box added by the compiler highlights the attachment filename beginning 'NSA_Traf_CAM_LONDON2847', which implies the image is an NSA traffic-camera capture from London.","text":"Q !UW.yye1fxo 02/16/18 (Fri) 18:26:57 No.99. File (hide): b11915573723c99....png (1.51 MB, 591x1280, 591:1280, NSA_Traf_CAM_LONDON2847. [UK] - Stay Alert. Q","people":[],"orgs":["NSA"],"objects":["Q post","traffic camera image","city street","traffic"],"places":["London","United Kingdom"],"terms":["Stay Alert","traffic cam","NSA_Traf_CAM","UK warning"],"flags":["Filename's claim that the photo is an NSA traffic camera capture of London is unverified; the street location cannot be confirmed from the dark image"],"confidence":"green"},
{"n":169,"kind":"photograph - aerial","description":"Photograph taken through an aircraft window at high altitude, looking down past scattered cumulus clouds at a hazy sea with several small dark islands and a sunlit horizon band at dusk or dawn. No landmarks are identifiable. The original Q filename '_AF1_5A_3.png' implies the photo was taken aboard Air Force One; nothing in the image itself confirms the aircraft or the location.","text":"","people":[],"orgs":[],"objects":["aircraft window view","clouds","islands","ocean"],"places":[],"terms":["Air Force One","AF1","window photo","aerial ocean","Asia trip"],"flags":["Filename implies the photo was taken from Air Force One - unverified","Location of the coastline/islands could not be identified"],"confidence":"red"},
{"n":179,"kind":"photograph","description":"Nighttime photograph of a crowded funfair with an illuminated carousel on the left, food and game stalls, and a red-and-green roller coaster with a partially readable illuminated sign (letters '...DE MA...', consistent with a 'Wilde Maus' style coaster). Crowds in winter clothing walk between the attractions. The Q filename 'CLAS_WW_UK_ACTIVE_T.png' is read by researchers as referring to Winter Wonderland in the UK (Hyde Park, London); the venue is consistent with that but not confirmed by anything visible.","text":"DE MA","people":[],"orgs":[],"objects":["roller coaster","carousel","fairground stalls","crowd","signpost"],"places":["Hyde Park Winter Wonderland (inferred from filename)","London","United Kingdom"],"terms":["Winter Wonderland","funfair","amusement park","CLAS_WW_UK","night crowd"],"flags":["Venue identified only by inference from the Q filename WW_UK; not confirmed from the image itself","Distant signage largely unreadable"],"confidence":"yellow"},
{"n":189,"kind":"screenshot - Q post","description":"Screenshot of Q post No. 148746 (tripcode !UW.yye1fxo, ID 42a0eb) dated 12/22/17, shown with a large block of reply links. Replying to post 148634, the drop reads 'MISSILE. MISSLE. FOX THREE. SPLASH. AS THE WORLD TURNS. RED_OCTOBER>'. 'Fox three' is fighter-pilot brevity code for an active-radar missile launch; the other lines are the drop's own cryptic phrases.","text":"Q !UW.yye1fxo 12/22/17 (Fri) 10:12:55 ID: 42a0eb No.148746. >>148750 >>148754 >>148764 >>148765 >>148767 >>148770 >>148781 >>148788 >>148792 >>148805 >>148811 >>148814 >>148815 >>148816 >>148823 >>148830 >>148831 >>148832 >>148838 >>148849 >>148856 >>148862 >>148922 >>148937 >>148939 >>148942 >>148945 >>148946 >>148950 >>149060 >>149074. >>148634. MISSILE. MISSLE. FOX THREE. SPLASH. AS THE WORLD TURNS. RED_OCTOBER> Q","people":[],"orgs":[],"objects":["Q post"],"places":[],"terms":["missile","Fox Three","splash","As The World Turns","Red October","brevity code"],"flags":["Drop content is the poster's cryptic claim; no verifiable event is shown"],"confidence":"green"},
{"n":199,"kind":"photograph","description":"Extreme close-up, partly blurred photograph of a white Google guest badge or lanyard card. The multicolored Google logo is visible at the top (rotated) and large black letters spelling the beginning of 'Guest' below; a bright blue plastic clip or holder crosses the middle of the frame. Attached to Q post 1501, where it was presented as evidence the poster was visiting Google; no location, person, or date is visible.","text":"Google. Gues","people":[],"orgs":["Google"],"objects":["guest badge","lanyard clip","visitor pass"],"places":[],"terms":["Google guest pass","visitor badge","close-up","Q proof"],"flags":["Photo shows only a badge fragment; where and when it was taken, and by whom, cannot be determined from the image"],"confidence":"green"},
]
with open(out,"a",encoding="utf-8") as f:
    for r in rows:
        f.write(json.dumps(r,ensure_ascii=False)+"\n")
print("appended",len(rows))
