// Outside-review verdicts on the entity uncertainty buckets.
//
// Recorded as DATA rather than folded into the classifier, so every decision is attributable
// and reversible. The classifier says what the evidence supports; this says what the review
// decided. Where they disagree, this wins — and the disagreement stays visible.

/** Bucket 1 — the 98 named-but-untyped records. */
export const BUCKET1 = {
  // routed out of Entities entirely
  QAnon: { route: 'themes', why: 'a movement/concept rather than a named organisation' },
  DECLAS: { route: 'themes_codes', why: 'Q shorthand for declassification — a code/theme, not a named thing' },
  'Wizards & Warlocks': { route: 'themes_codes', why: 'no specific referent established' },

  // typed
  MS13: { type: 'organization', canonical: 'MS-13' },
  MS_13: { type: 'organization', canonical: 'MS-13', mergedInto: 'MS-13' },
  'MS-13': { type: 'organization', canonical: 'MS-13' },
  McCain: { type: 'person', canonical: 'John McCain' },
  ASIA: { type: 'country_region', canonical: 'Asia' },
  Ohr: { type: 'person', canonical: 'Bruce Ohr' },
  SCIF: { type: 'facility_property', canonical: 'SCIF' },
  WHITAKER: { type: 'person', canonical: 'Matthew Whitaker' },
  LifeLog: { type: 'program_operation_project', canonical: 'LifeLog' },
  USMC: { type: 'government_agency', canonical: 'United States Marine Corps' },
  'Sec of State': { type: 'title_role', canonical: 'Secretary of State' },
  'SEC of STATE': { type: 'title_role', canonical: 'Secretary of State', mergedInto: 'Secretary of State' },
  SpaceX: { type: 'organization', canonical: 'SpaceX' },
  Breaking911: { type: 'media_organization', canonical: 'Breaking911' },
  'C-SPAN': { type: 'media_organization', canonical: 'C-SPAN' },
  'AT&T': { type: 'organization', canonical: 'AT&T' },
  '/pol/': { type: 'technology_platform', canonical: '/pol/' },
  'Bush family': { type: 'other_named_entity', canonical: 'Bush family', why: 'a named family rather than one person' },
  WRAY: { type: 'person', canonical: 'Christopher Wray' },
  NYPD: { type: 'government_agency', canonical: 'New York Police Department' },
  '4ch': { type: 'technology_platform', canonical: '4chan' },
  '8chan': { type: 'technology_platform', canonical: '8chan' },
  MarketWatch: { type: 'media_organization', canonical: 'MarketWatch' },
  'Gang of Eight': { type: 'government_institution', canonical: 'Gang of Eight' },
  'Gang of 8': { type: 'government_institution', canonical: 'Gang of Eight', mergedInto: 'Gang of Eight' },
  RealClearPolitics: { type: 'media_organization', canonical: 'RealClearPolitics' },
  TIME: { type: 'media_organization', canonical: 'TIME' },
  OpenSecrets: { type: 'organization', canonical: 'OpenSecrets' },
  SOTU: { type: 'event_incident', canonical: 'State of the Union' },
  Xi: { type: 'person', canonical: 'Xi Jinping' },
  '23andMe': { type: 'organization', canonical: '23andMe' },
  '9-11': { type: 'event_incident', canonical: 'September 11 attacks' },
  'Paris accord': { type: 'legislation_regulation', canonical: 'Paris Agreement' },
  MOAB: { type: 'military_asset_vessel', canonical: 'MOAB' },
  'John J. Duncan, Jr.': { type: 'person', canonical: 'John J. Duncan Jr.' },
  'John Conyers, Jr.': { type: 'person', canonical: 'John Conyers Jr.' },
  GoFundMe: { type: 'technology_platform', canonical: 'GoFundMe' },
  WWII: { type: 'event_incident', canonical: 'World War II' },
  HuffingtonPost: { type: 'media_organization', canonical: 'HuffPost' },
  FOIA: { type: 'legislation_regulation', canonical: 'Freedom of Information Act' },
  Vox: { type: 'media_organization', canonical: 'Vox' },
  INSCOM: { type: 'government_agency', canonical: 'INSCOM' },
  '2016 Presidential election': { type: 'event_incident', canonical: '2016 Presidential election' },
  '2020 election': { type: 'event_incident', canonical: '2020 election' },
  'Guccifer 2.0': { type: 'coded_alias', canonical: 'Guccifer 2.0' },
  STRZOK: { type: 'person', canonical: 'Peter Strzok' },
  REDDIT: { type: 'technology_platform', canonical: 'Reddit' },
  'Declaration of Independence': { type: 'other_named_entity', canonical: 'Declaration of Independence', why: 'a named historical document' },
  PlayStation: { type: 'technology_platform', canonical: 'PlayStation' },
  GHWB: { type: 'person', canonical: 'George H. W. Bush' },
  BuzzFeed: { type: 'media_organization', canonical: 'BuzzFeed' },
  MKUltra: { type: 'program_operation_project', canonical: 'MKUltra' },
  ICANN: { type: 'organization', canonical: 'ICANN' },
  'McKinsey & Company': { type: 'organization', canonical: 'McKinsey & Company' },
  WattersWorld: { type: 'creative_work', canonical: "Watters' World" },
  IngrahamAngle: { type: 'creative_work', canonical: 'The Ingraham Angle' },
  McMaster: { type: 'person', canonical: 'H. R. McMaster' },
  'military.com': { type: 'media_organization', canonical: 'Military.com' },
  ODNI: { type: 'government_agency', canonical: 'Office of the Director of National Intelligence' },
  'Office of the Director of National Intelligence': { type: 'government_agency', canonical: 'Office of the Director of National Intelligence' },
  ActBlue: { type: 'organization', canonical: 'ActBlue' },
  NewsBreak: { type: 'media_organization', canonical: 'NewsBreak' },
  CodeMonkey: { type: 'coded_alias', canonical: 'CodeMonkey' },
  CISA: { type: 'government_agency', canonical: 'CISA' },
  SecureDrop: { type: 'technology_platform', canonical: 'SecureDrop' },
  'Abdullah bin Abdulaziz': { type: 'person', canonical: 'Abdullah bin Abdulaziz' },
  'Clinton Health Access Initiative': { type: 'organization', canonical: 'Clinton Health Access Initiative' },
  'Telecommunications Act of 1996': { type: 'legislation_regulation', canonical: 'Telecommunications Act of 1996' },
  'Insurrection Act of 1807': { type: 'legislation_regulation', canonical: 'Insurrection Act of 1807' },
  'Atomic Energy Act of 1954': { type: 'legislation_regulation', canonical: 'Atomic Energy Act of 1954' },
  'Waukesha South High School': { type: 'facility_property', canonical: 'Waukesha South High School' },
  'National Presidential Alert System': { type: 'program_operation_project', canonical: 'National Presidential Alert System' },
  'Bill de Blasio': { type: 'person', canonical: 'Bill de Blasio' },
  'Banco de Mexico': { type: 'financial_institution', canonical: 'Banco de México' },
  'COVID-19': { type: 'other_named_entity', canonical: 'COVID-19', why: 'no disease/health-event type exists, and one is not invented for a handful of cases' },

  // account handles — a real referent, but a handle rather than a resolved identity
  michaelbeatty3: { type: 'coded_alias', canonical: '@michaelbeatty3', why: 'account handle' },
  GeorgePapa19: { type: 'coded_alias', canonical: '@GeorgePapa19', why: 'account handle' },
  Scavino45: { type: 'coded_alias', canonical: '@Scavino45', why: 'account handle' },
  JeffDeRiso: { type: 'coded_alias', canonical: '@JeffDeRiso', why: 'account handle' },
  M2Madness: { type: 'coded_alias', canonical: '@M2Madness', why: 'account handle' },

  // left unresolved by review
  Kim: { unresolved: 'surname and given name share the token' },
  AWAN: { unresolved: 'the Awan individual or family only where context supports it' },
  DEFCON: { unresolved: 'an event in some drops and a readiness condition in others' },
  'J C': { unresolved: 'initials with more than one referent' },
  PAGE: { unresolved: 'a person only where context establishes it' },
  Pol: { unresolved: 'shorthand for /pol/ only where context establishes it' },
  May: { unresolved: 'a month and a surname' },
  Rod: { unresolved: 'a given name with more than one referent' },
  Bob: { unresolved: 'a given name with more than one referent' },
  LdR: { unresolved: 'initials with more than one referent' },
  B2: { unresolved: 'a bomber only where context establishes it' },
  Dan: { unresolved: 'a given name with more than one referent' },
  APACHE: { unresolved: 'aircraft, tribe, or software depending on the drop' },
  DELTA: { unresolved: 'more than one referent across the corpus' },
  Bill: { unresolved: 'a given name and an ordinary noun' },
}

/** Bucket 2 — acronyms strong enough to resolve on the token alone. */
export const SAFE_GLOBAL = {
  ABC: { canonical: 'ABC News', type: 'media_organization' },
  DNI: { canonical: 'Director of National Intelligence', type: 'title_role' },
  NYC: { canonical: 'New York City', type: 'location' },
  CDC: { canonical: 'Centers for Disease Control and Prevention', type: 'government_agency' },
  WHO: { canonical: 'World Health Organization', type: 'organization' },
  BBC: { canonical: 'BBC', type: 'media_organization' },
  RBG: { canonical: 'Ruth Bader Ginsburg', type: 'person' },
  NSC: { canonical: 'National Security Council', type: 'government_institution' },
  MZ: { canonical: 'Mark Zuckerberg', type: 'person' },
  NPR: { canonical: 'NPR', type: 'media_organization' },
  'U.S.': { canonical: 'United States', type: 'country_region' },
  IRS: { canonical: 'Internal Revenue Service', type: 'government_agency' },
  WSJ: { canonical: 'The Wall Street Journal', type: 'media_organization' },
  DHS: { canonical: 'Department of Homeland Security', type: 'government_agency' },
  CBS: { canonical: 'CBS', type: 'media_organization' },
  ICE: { canonical: 'Immigration and Customs Enforcement', type: 'government_agency' },
  AZ: { canonical: 'Arizona', type: 'location' },
  TX: { canonical: 'Texas', type: 'location' },
  KKK: { canonical: 'Ku Klux Klan', type: 'political_group_movement' },
  UN: { canonical: 'United Nations', type: 'organization' },
  UBL: { canonical: 'Osama bin Laden', type: 'person' },
  PBS: { canonical: 'PBS', type: 'media_organization' },
  DAG: { canonical: 'Deputy Attorney General', type: 'title_role' },
  EPA: { canonical: 'Environmental Protection Agency', type: 'government_agency' },
  NZ: { canonical: 'New Zealand', type: 'country_region' },
  WWI: { canonical: 'World War I', type: 'event_incident' },
  CFR: { canonical: 'Council on Foreign Relations', type: 'organization' },
  SIS: { canonical: 'Secret Intelligence Service', type: 'government_agency', note: 'UK SIS where corpus context supports it' },
  FED: { canonical: 'Federal Reserve', type: 'government_institution', note: 'only where clearly the Federal Reserve' },
  GER: { canonical: 'Germany', type: 'country_region', note: 'only where used as country shorthand' },
}

/** Bucket 2 — routed out of Entities. */
export const ROUTE_OUT = {
  RED_OCTOBER: 'themes_codes',
  D_PARTY: 'themes',
  CASTLE_ROCK: 'themes_codes',
}

/**
 * Bucket 2 — probe these post by post. A referent is assigned ONLY where the surrounding
 * lines carry explicit evidence; everything else stays unresolved.
 */
export const CONTEXT_RESOLVE = {
  DC: [{ canonical: 'Washington, D.C.', type: 'location', evidence: /\b(washington|capitol|district|beltway|swamp|congress|white house)\b/i }],
  Clinton: [
    { canonical: 'Hillary Clinton', type: 'person', evidence: /\b(hillary|hrc|secretary of state|email|server|benghazi|she|her)\b/i },
    { canonical: 'Bill Clinton', type: 'person', evidence: /\b(bill|impeach|lewinsky|1990s|husband|former president)\b/i },
  ],
  BO: [
    { canonical: 'Board Owner', type: 'title_role', evidence: /\b(board|owner|8ch|8kun|bv\b|mod\b|codemonkey)\b/i },
    { canonical: 'Barack Obama', type: 'person', evidence: /\b(obama|hussein|renegade|president|potus)\b/i },
  ],
  SC: [{ canonical: 'Supreme Court', type: 'legal_investigative', evidence: /\b(court|justice|nominee|scotus|bench|confirm)\b/i }],
  LL: [{ canonical: 'Loretta Lynch', type: 'person', evidence: /\b(lynch|tarmac|attorney general|ag\b|doj)\b/i }],
  CA: [{ canonical: 'California', type: 'location', evidence: /\b(california|newsom|los angeles|san francisco|state of)\b/i }],
  JC: [
    { canonical: 'James Comey', type: 'person', evidence: /\b(comey|fbi|director|memo)\b/i },
    { canonical: 'Jesus Christ', type: 'religious_spiritual', evidence: /\b(god|lord|pray|faith|amen|christ)\b/i },
  ],
  JFK: [
    { canonical: 'John F. Kennedy', type: 'person', evidence: /\b(kennedy|assassinat|1963|dallas|grassy)\b/i },
    { canonical: 'JFK Airport', type: 'facility_property', evidence: /\b(airport|flight|terminal|runway|landed)\b/i },
  ],
  AUS: [{ canonical: 'Australia', type: 'country_region', evidence: /\b(australia|aussie|canberra|downer|sydney)\b/i }],
  BC: [{ canonical: 'Bill Clinton', type: 'person', evidence: /\b(clinton|impeach|lewinsky|foundation)\b/i }],
  JA: [{ canonical: 'Julian Assange', type: 'person', evidence: /\b(assange|wikileaks|embassy|ecuador|extradit)\b/i }],
  WL: [{ canonical: 'WikiLeaks', type: 'organization', evidence: /\b(wikileaks|assange|leak|dump|release)\b/i }],
  MI: [
    { canonical: 'Military Intelligence', type: 'government_agency', evidence: /\b(military|intel|army|dia|operation)\b/i },
    { canonical: 'Michigan', type: 'location', evidence: /\b(michigan|detroit|whitmer|state of)\b/i },
  ],
  VJ: [{ canonical: 'Valerie Jarrett', type: 'person', evidence: /\b(jarrett|valerie|adviser|white house|hussein)\b/i }],
  SR: [{ canonical: 'Seth Rich', type: 'person', evidence: /\b(seth|rich|dnc|murder|wheeler|leak)\b/i }],
  GS: [{ canonical: 'George Soros', type: 'person', evidence: /\b(soros|george|open society|funding)\b/i }],
  BLM: [
    { canonical: 'Black Lives Matter', type: 'political_group_movement', evidence: /\b(protest|riot|floyd|movement|racial)\b/i },
    { canonical: 'Bureau of Land Management', type: 'government_agency', evidence: /\b(land|bureau|federal land|grazing|bundy)\b/i },
  ],
  DWS: [{ canonical: 'Debbie Wasserman Schultz', type: 'person', evidence: /\b(wasserman|schultz|dnc|awan|florida)\b/i }],
  GA: [{ canonical: 'Georgia', type: 'location', evidence: /\b(georgia|atlanta|fulton|state of|county)\b/i }],
  LV: [{ canonical: 'Las Vegas', type: 'location', evidence: /\b(vegas|nevada|mandalay|paddock|shooting)\b/i }],
  NY: [{ canonical: 'New York', type: 'location', evidence: /\b(new york|manhattan|nyc|state of|city)\b/i }],
  Maxwell: [{ canonical: 'Ghislaine Maxwell', type: 'person', evidence: /\b(ghislaine|epstein|island|trafficking)\b/i }],
  HK: [{ canonical: 'Hong Kong', type: 'country_region', evidence: /\b(hong kong|china|protest|beijing)\b/i }],
}
